// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdykatenugsicxcvyqwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkeWthdGVudWdzaWN4Y3Z5cXdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5NzU5OTgsImV4cCI6MjA1MTU1MTk5OH0.Jr6K5OIJKHtdZDy7vUCQfSATujs_XwIpPCiICpJNVuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);